### ISSUE TITLE
Bug report: no content in the window

### ISSUE THREAD

**Issue by Kuri-su** [MixinNetwork/flutter-app#525]
![image](https://user-images.githubusercontent.com/22676438/154471520-a484c196-5e82-44d3-9cfe-6dec33b203d4.png)
```
icon path: /usr/lib/mixin_desktop/data/flutter_assets/assets/icons/windows_app_icon.pngsystem_tray_plugin_class_init klass: 0x1b27dd0
system_tray_plugin_init self: 0x1c008d0
```

file `/usr/lib/mixin_desktop/data/flutter_assets/assets/icons/windows_app_icon.png` is exists

from: 
```
 ~ $ cat /etc/lsb-release                                       
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
```

**Comment by crossle** [comment]
https://github.com/MixinNetwork/flutter-app#debian

**Comment by Kuri-su** [comment]
or maybe i need to report some log in anywhere?

**Comment by crossle** [comment]
try `sudo apt-get install appindicator3-0.1 libappindicator3-dev`

**Comment by boyan01** [comment]
deb already include a CONTROL file.  https://github.com/MixinNetwork/flutter-app/blob/30b2d4c19b0859c1bda2ab12fe94817897e85b14/dist/deb/DEBIAN/control#L8 

`sudo apt-get install -f` should auto install all needed dependecy package.

the `icon path` and `system_tray_plugin_class` are just  normal log...

**Comment by Kuri-su** [comment]
i will try it later
