### ISSUE TITLE
building on linux / debian requires obsolete package

### ISSUE THREAD

**Issue by suddenlyfleck** [MixinNetwork/flutter-app#533]
Hi,

I wanted to try out the Mixin desktop app.

On the current debian stable branch, the dependencies in the readme [readme](https://github.com/MixinNetwork/flutter-app#readme) are not available. Both packages, `libappindicator3-dev` and `gir1.2-appindicator3-0.1` are listed as [obsolete packages](https://www.debian.org/releases/bullseye/amd64/release-notes/ch-information.en.html#noteworthy-obsolete-packages).
They state that "debian is using **libayatana-appindicator** as the successor of libappindicator."

As of right now, I am unable to `flutter build linux --release` since "A required package was not found" which I guess is this app-indicator.

I'd really like to try out the Mixin flutter app.

Will you update to libayatana-appindicator, or what will be done?

Thanks for considering.

Keep up the great work!

**Comment by crossle** [comment]
Thanks, good suggestions, we use https://pub.dev/packages/system_tray so it's use the libappindicator3. We can look for better alternatives or do it ourselves.
