### ISSUE TITLE
Windows run error.

### ISSUE THREAD

**Issue by iamxvbaba** [MixinNetwork/flutter-app#566]
![image](https://user-images.githubusercontent.com/28732408/159116649-f33e929b-c0b5-423a-9d52-c831a4a1cb39.png)

**Comment by boyan01** [comment]
It looks like you are not using the master channel?  this project required run with flutter master channel.

You can use flowing command to switch your flutter to master channel.

```
flutter channel master
```

**Comment by iamxvbaba** [comment]
> It looks like you are not using the master channel? this project required run with flutter master channel.
> 
> You can use flowing command to switch your flutter to master channel.
> 
> ```
> flutter channel master
> ```

thanks.
