### ISSUE TITLE
flutter run -d windows failed

### ISSUE THREAD

**Issue by smelike** [MixinNetwork/flutter-app#718]
operate system: windows 11 21H2 (22000.739)

info: 
`
 flutter run -d windows
Launching lib\main.dart on Windows in debug mode...
lib/utils/system/tray.dart(44,11): error G837C20CB: 'MenuItem' is imported from both 'package:flutter/src/widgets/platform_menu_bar.dart' and 'package:system_tray/src/menu_item.dart'. [D:\playhouse\labs\flutter-app-0.22.0\build\windows\flutter\flutter_assemble.vcxproj]
lib/utils/system/tray.dart(51,11): error G837C20CB: 'MenuItem' is imported from both 'package:flutter/src/widgets/platform_menu_bar.dart' and 'package:system_tray/src/menu_item.dart'. [D:\playhouse\labs\flutter-app-0.22.0\build\windows\flutter\flutter_assemble.vcxproj]
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/bitsdojo_window-0.1.1+1/lib/src/widgets/mouse_state_builder.dart(60,30): warning GBC99161D: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null. [D:\playhouse\labs\flutter-app-0.22.0\build\windows\flutter\flutter_assemble.vcxproj]
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_hooks-0.18.2+1/lib/src/widgets_binding_observer.dart(42,29): warning GBC99161D: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null. [D:\playhouse\labs\flutter-app-0.22.0\build\windows\flutter\flutter_assemble.vcxproj]
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_hooks-0.18.2+1/lib/src/widgets_binding_observer.dart(43,20): warning GBC99161D: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null. [D:\playhouse\labs\flutter-app-0.22.0\build\windows\flutter\flutter_assemble.vcxproj]
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_hooks-0.18.2+1/lib/src/widgets_binding_observer.dart(52,20): warning GBC99161D: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null. [D:\playhouse\labs\flutter-app-0.22.0\build\windows\flutter\flutter_assemble.vcxproj]
/C:/src/flutter/.pub-cache/git/bitsdojo_window-78faaa6440c7fee146258bb0ef3336c33ed4555d/bitsdojo_window_windows/lib/src/bitsdojo_window_windows_real.dart(17,20): warning GBC99161D: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null. [D:\playhouse\labs\flutter-app-0.22.0\build\windows\flutter\flutter_assemble.vcxproj]
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/bitsdojo_window_macos-0.1.0/lib/src/bitsdojo_window_macos_real.dart(13,20): warning GBC99161D: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null. [D:\playhouse\labs\flutter-app-0.22.0\build\windows\flutter\flutter_assemble.vcxproj]
/C:/src/flutter/.pub-cache/git/bitsdojo_window-78faaa6440c7fee146258bb0ef3336c33ed4555d/bitsdojo_window_linux/lib/src/bitsdojo_window_linux_real.dart(14,20): warning GBC99161D: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null. [D:\playhouse\labs\flutter-app-0.22.0\build\windows\flutter\flutter_assemble.vcxproj]
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/scrollable_positioned_list-0.2.3/lib/src/scrollable_positioned_list.dart(439,24): warning GBC99161D: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null. [D:\playhouse\labs\flutter-app-0.22.0\build\windows\flutter\flutter_assemble.vcxproj]
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/scrollable_positioned_list-0.2.3/lib/src/scrollable_positioned_list.dart(486,26): warning GBC99161D: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null. [D:\playhouse\labs\flutter-app-0.22.0\build\windows\flutter\flutter_assemble.vcxproj]
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/system_tray-0.1.0/lib/src/tray.dart(9,1): error G837C20CB: 'MenuItem' is imported from both 'package:flutter/src/widgets/platform_menu_bar.dart' and 'package:system_tray/src/menu_item.dart'. [D:\playhouse\labs\flutter-app-0.22.0\build\windows\flutter\flutter_assemble.vcxproj]
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-4.2.1/lib/src/extended_image.dart(774,20): warning GBC99161D: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null. [D:\playhouse\labs\flutter-app-0.22.0\build\windows\flutter\flutter_assemble.vcxproj]
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-4.2.1/lib/src/extended_image.dart(782,20): warning GBC99161D: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null. [D:\playhouse\labs\flutter-app-0.22.0\build\windows\flutter\flutter_assemble.vcxproj]
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image-4.2.1/lib/src/extended_image.dart(863,26): warning GBC99161D: Operand of null-aware operation '!' has type 'SemanticsBinding' which excludes null. [D:\playhouse\labs\flutter-app-0.22.0\build\windows\flutter\flutter_assemble.vcxproj]
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/scrollable_positioned_list-0.2.3/lib/src/positioned_list.dart(312,24): warning GBC99161D: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null. [D:\playhouse\labs\flutter-app-0.22.0\build\windows\flutter\flutter_assemble.vcxproj]
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-3.1.2/lib/src/extended_image_provider.dart(28,30): warning GBC99161D: Operand of null-aware operation '!' has type 'PaintingBinding' which excludes null. [D:\playhouse\labs\flutter-app-0.22.0\build\windows\flutter\flutter_assemble.vcxproj]
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-3.1.2/lib/src/extended_image_provider.dart(28,40): warning GBC99161D: Operand of null-aware operation '!' has type 'ImageCache' which excludes null. [D:\playhouse\labs\flutter-app-0.22.0\build\windows\flutter\flutter_assemble.vcxproj]
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-3.1.2/lib/src/extended_image_provider.dart(97,39): warning GBC99161D: Operand of null-aware operation '!' has type 'PaintingBinding' which excludes null. [D:\playhouse\labs\flutter-app-0.22.0\build\windows\flutter\flutter_assemble.vcxproj]
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-3.1.2/lib/src/platform.dart(26,21): warning GBC99161D: Operand of null-aware operation '?.' has type 'PaintingBinding' which excludes null. [D:\playhouse\labs\flutter-app-0.22.0\build\windows\flutter\flutter_assemble.vcxproj]
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-3.1.2/lib/src/platform.dart(27,21): warning GBC99161D: Operand of null-aware operation '?.' has type 'PaintingBinding' which excludes null. [D:\playhouse\labs\flutter-app-0.22.0\build\windows\flutter\flutter_assemble.vcxproj]
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/extended_image_library-3.1.2/lib/src/platform.dart(40,28): warning GBC99161D: Operand of null-aware operation '?.' has type 'PaintingBinding' which excludes null. [D:\playhouse\labs\flutter-app-0.22.0\build\windows\flutter\flutter_assemble.vcxproj]
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/visibility_detector-0.2.2/lib/src/visibility_detector_layer.dart(126,28): warning GBC99161D: Operand of null-aware operation '?.' has type 'RendererBinding' which excludes null. [D:\playhouse\labs\flutter-app-0.22.0\build\windows\flutter\flutter_assemble.vcxproj]
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/visibility_detector-0.2.2/lib/src/visibility_detector_layer.dart(127,50): warning GBC99161D: Operand of null-aware operation '!' has type 'RendererBinding' which excludes null. [D:\playhouse\labs\flutter-app-0.22.0\build\windows\flutter\flutter_assemble.vcxproj]
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/visibility_detector-0.2.2/lib/src/visibility_detector_layer.dart(170,26): warning GBC99161D: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null. [D:\playhouse\labs\flutter-app-0.22.0\build\windows\flutter\flutter_assemble.vcxproj]
/C:/src/flutter/.pub-cache/hosted/pub.dartlang.org/visibility_detector-0.2.2/lib/src/visibility_detector_layer.dart(193,22): warning GBC99161D: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null. [D:\playhouse\labs\flutter-app-0.22.0\build\windows\flutter\flutter_assemble.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: ��D:\playhouse\labs\flutter-app-0.22.0\build\windows\CMakeFiles\17e6e1763169a013a4414284245f23b3\flutter_windows.dll.rule;D:\playhouse\labs\flutter-app-0.22.0\build\windows\CMakeFiles\2e846aa6cc3048fbc5844e1f9953ea90\flutter_assemble.rule�����Զ����������˳�������Ϊ 1�� [D:\playhouse\labs\flutter-app-0.22.0\build\windows\flutter\flutter_assemble.vcxproj]
Building Windows application...
Exception: Build process failed.
`

**Comment by boyan01** [comment]
Please use latest stable flutter.

``` 
flutter channel stable

flutter upgrade
```

**Comment by smelike** [comment]
> Please switch you flutter version to latest stable channel.
> 
> ```
> flutter channel stable
> 
> flutter upgrade
> ```

`flutter --version
Flutter 3.0.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 85684f9300 (11 days ago) • 2022-06-30 13:22:47 -0700
Engine • revision 6ba2af10bb
Tools • Dart 2.17.5 • DevTools 2.12.2`

**Comment by boyan01** [comment]
> flutter-app-0.22.0

 Are you compiling the version 0.22.0 ?  you can checkout the latest main branch instead.
