### ISSUE TITLE
I need implementation of auto-update on Mixin flutter desktop, please

### ISSUE THREAD

**Issue by Lazizbek97** [MixinNetwork/flutter-app#725]
Hello Mixin Flutter comunity! You guys have done great work with flutter on desktop. If possible, please, share your experience with implementing auto-update on flutter desktop app. Actually this is not issue, but I really need your help!

**Comment by crossle** [comment]
https://github.com/MixinNetwork/flutter-app/issues/298#issuecomment-1042837013
